### ISSUE TITLE
PCB printing

### ISSUE THREAD

**Issue by cplagz** [lspaula/Nextion-background-for-HASwitchPlate#1]
Great work on the 3.5" setup.  I haven't done much with printing PCBs before, is there much difference in yours and luma's original design?  I'd rather buy his from tindie store if possible to use with 3.5.  Sorry for using issue page to contact.

**Comment by lspaula** [comment]
Hello. It is very similar to his design. I've made mine in order to fit the standard 4x2 box, as well. I think that the only difference is that mine uses the Hi-link (hlk-pm01) instead of the IRM-03-05.
